#服务端口
server:
  port: 8200

spring:
  datasource:
    username: root
    password: daasan7ujm^YHN
    url: jdbc:mysql://47.101.41.147/insuranceDB?Unicode=utf8$characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    #应用程序名称
    name: insurance-provider-Warranty2
    #注册中心配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #在consul对外暴露的服务名称
        service-name: ${spring.application.name}
        #主机名称
        hostname: 127.0.0.1
        #是否注册到注册中心
        register: true
mybatis:
    type-aliases-package: com.ytl.insurance.pojo
    mapper-locations: classpath:mapper/*.xml